checks:
  php: true
build:
  nodes:
    tests: true
    analysis:
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true
          - php-scrutinizer-run
filter:
  excluded_paths:
    - tests/*