language: php

php:
  - '7.1'
  - '7.2'
  - nightly
  - hhvm

before_install:
  # Force HHVM PHP 7 mode
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

before_script:
  - composer self-update
  - composer install

script:
  - composer test

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

notifications:
  on_success: never
  on_failure: always