language: php

php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update
  - composer install

script:
  - composer test

matrix:
  allow_failures:
    - php: nightly

notifications:
  on_success: never
  on_failure: always