language: php

php:
  - '5.6'
  - '7.1'
  - '7.2'
  - nightly
  - hhvm
  
before_script:
  - composer self-update
  - composer install 
  
script:
  - composer test
 
matrix:
  allow_failures:
    - php: '5.6'
    - php: nightly
    - php: hhvm

notifications:
  on_success: never
  on_failure: always